### PR TITLE
adding support for prepend and append

### PR DESCRIPTION
**Pull request by leastbad**
# Type of PR (feature, enhancement, bug fix, etc.)

Enhancement

## Description

Adjacent to data-reflex-root, this PR adds the ability to mark a reflex-root element with either `data-reflex-append` or `data-reflex-prepend`. Inspired by [LiveView custom DOM patching](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-custom-dom-patching).

Tandem PR with [Cable Ready PR 19](https://github.com/hopsoft/cable_ready/pull/19).

## Why should this be added

Highly useful for chat interfaces, newsfeeds and any application that maintains a cursor inside of a larger document.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing

### CODE REVIEW

**Comment by hopsoft** [comment]
This is interesting but I'd like to hold on the feature until a real world use case forces the need.

**Comment by hopsoft** [comment]
When we do revisit this, I think I'd prefer to look at CableReady's [`insertAdjacentHTML`](https://cableready.stimulusreflex.com/usage/dom-operations/element-mutations#insertadjacenthtml).

**Comment by pjforde1978** [comment]
I actually addressed this in the [tandem PR](https://github.com/hopsoft/cable_ready/pull/19).

Happy to hold this one in the queue; nothing I'm working on relies on this.

**Comment by leastbad** [comment]
This functionality is best achieved by using [CableReady](https://cableready.stimulusreflex.com)'s insertAdjacentHTML method.

**Pull request closed without merging**
