### PR TITLE
Proposal: Reduce bundle size and add a bundler for Stimulus Reflex javascript

### PR DESCRIPTION
**Pull request by ParamagicDev**
# Type of PR (feature, enhancement, bug fix, etc.)

Proposal

## Description

Move `@rails/actioncable`, `stimulus`, and `cable_ready` to `peerDependencies`

Add `cable_ready` to the install task.

Add [microbundle](https://github.com/developit/microbundle) to bundle javascript for publishing.

## Why should this be added

By moving these `dependencies` to `peerDependencies`, it will reduce the size of StimulusReflex's package and remove any possible version issues between user defined packages and the packages SR ships.

Adding a Bundler helps SR run in different environments.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing

### CODE REVIEW

**Comment by leastbad** [comment]
Even your git commit messages are top notch

**Review by hopsoft — APPROVED** [review]

**Comment by leastbad** [comment]
FYI: I have great faith in @ParamagicDev but I haven't tested this PR and am not 100% confident I could explain the ramifications to someone in a bar. @hopsoft what is your confidence interval?

**Comment by ParamagicDev** [comment]
@leastbad So here's my $0.02, to start, yes there are trade offs.

In summary by moving ActionCable, CableReady, and Stimulus to peerDependencies, it means the user has to install them and it uses whatever the user has installed. If it does not match the version or the peerDependency, it will output a warning to the user when they `yarn install`.

The trade off is StimulusReflex does not have explicit versioning, however, it also means that users don't have 2 instances of ActionCable, CableReady, and Stimulus if they installed them in their project separate of StimulusReflex.

**Comment by leastbad** [comment]
Thanks to @ParamagicDev, I'm now on a `peerDependencies` roll.

**Pull request merged**
