### PR TITLE
Support for Stimulus 2

### PR DESCRIPTION
**Pull request by marcoroth**
# Type of PR

Enhancement

## Description

Seems like this is the only thing we need to do in order to use Stimulus 2 but still support Stimulus 1.x. We are not using `data-target` inside the StimulusReflex project itself so it seems most of the changes need to be done in user-land.

## Why should this be added

Keep up to date with the latest Stimulus

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing
- [x] This is not a documentation update

### CODE REVIEW

**Comment by hopsoft** [comment]
Nice. Have you tested with Stimulus 2.0?

**Comment by marcoroth** [comment]
Yes, I tried to run both Expo and Boxdrop. Everything seems to work as intended. The only thing I noticed is the `data-target` deprecation warnings, but other than that it seems good. But will keep it as draft as of now.

**Comment by leastbad** [comment]
Thanks so much for doing this, @marcoroth! I'd had serious problems with one of the later builds and SR; glad the problem 👻ed.

What a relief!

**Comment by hopsoft** [comment]
FYI - I'm running @marcoroth's branch for this PR in staging for a production app with Stimulus 2. So far, so good.

**Review by hopsoft — APPROVED** [review]

**Pull request merged**
