### PR TITLE
Setup a proxy object that wraps CableReady::Channels

### PR DESCRIPTION
**Pull request by hopsoft**
# Enhancement

## Description

Expose `cable_ready` to reflexes through a proxy object to improve the developer ergonomics when emitting CableReady broadcasts from within a reflex _on the StimulusReflex channel_.

## Example Usage

```ruby
class ExampleReflex < ApplicationReflex
  def do_stuff
    # business logic....

    cable_ready
      .push_state(url: "https://example.com/123")
      .dispatch_event(name: "wtf", detail: {message: "Holy shit!"})
      .broadcast

    # default behavior of full page render + update still runs
    # you could also opt to call: morph [SELECTOR, :nothing] here
  end
end
```

Note this is the server side counter part to #381 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing
- [x] This is not a documentation update

### CODE REVIEW

**Comment by marcoroth** [comment]
Nice, this really improves the developer experience!

**Comment by hopsoft** [comment]
We should be careful not to encourage element mutations via CableReady if/when someone is using default reflex behavior.

**Comment by leastbad** [comment]
I will be addressing this in the docs, 100%.

One thing that might not be self-evident from the readme above is that this also implicitly solves the "how do I send a CableReady broadcast just to the current user" question, at least within a Reflex.

**Comment by hopsoft** [comment]
This blurs the line a little if someone is using morphs. For example, what is our recommendation on when to use morphs vs cable_ready directly?

**Comment by julianrubisch** [comment]
Can we use this also to decouple the broadcasters?

Comes to mind because I mocked CableReady::Channels pretty often in the tests

**Comment by leastbad** [comment]
Someone wise suggested that the easy way to decide if you need a CableReady#morph vs a CableReady operation is whether you need StimulusReflex callbacks on the client afterwards.

**Comment by hopsoft** [comment]
@julianrubisch Yes, I expect this to open up some refactoring opportunities in the broadcasters, tests, and possibly elsewhere.

**Comment by julianrubisch** [comment]
So I‘m playing bad cop (again) - could you add some exemplary tests for `StimulusReflex::CableReadyChannels` ? This will further (my) understanding and facilitate future refactorings...

**Comment by hopsoft** [comment]
Yes and thank you for pushing hard on the tests @julianrubisch.

**Comment by RolandStuder** [comment]
Nice stuff!

> We should be careful not to encourage element mutations via CableReady if/when someone is using default reflex behavior.

Could the proxy object not actually somehow prevent that by declaring a `morph :nothing`?

**Comment by leastbad** [comment]
Another **excellent** reason to require `broadcast` is that - at least right now - if they piggyback CR operations that aren't SR-specific on a broadcast that has SR operations, well, very bad things. As currently implemented, it would actually break because the code assumes every `dispatchEvent`/`morph`/`innerHtml` has a `stimulusReflex` accessor. All other operations would be silently discarded. Obviously not desireable.

I am going to have to make another pass on `received` that is more robust. I need to separate the `data.operations` into two objects: one that has `stimulusReflex` accessors and one that doesn't.

**Pull request merged**
