### PR TITLE
Check the ActionCable connection on stimuluate

### PR DESCRIPTION
**Pull request by hopsoft**
# Feature

## Description

Raise and exception if stimuluate is called before the ActionCable connection is open and ready.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing

### CODE REVIEW

**Comment by leastbad** [comment]
This is a really good step in the right direction.

1. Can we also merge #86 alongside this? It probably needs to be rebased, but conceptually this is valid and viable.
2. What happens if stimulate is triggered by a declared reflex? I guess the error will raise but there's no opportunity to capture it.

**Comment by julianrubisch** [comment]
👆🏻 2. was also my first thought?

**Comment by hopsoft** [comment]
1. I'm not sure how I feel about #86 after revisiting it. I now consider it to be a concern that should be managed by users of the library. _But, we can and should provide documentation to help users understand how to best work with the socket connection in their controllers._ Here's an example:

```js
export default class extends ApplicationController {
  connect () {
    super.connect()
    this.doStuff()
  }

  doStuff () {
    if (!this.isActionCableConnectionOpen()) 
      return setTimeout(this.doStuff.bind(this), 10)
    this.stimulate('ExampleReflex#do_stuff')
  }
}
```

2. This is already a problem today. The primary difference is that users don't currently get a helpful error message. I expect that in the future we may be able to implicitly check the connection status on `stimulate` and retry until the connection is ready, but we'll need to be thoughtful about this. Also, I see that feature as landing as a separate feature in a new PR.

**Comment by leastbad** [comment]
1. I hope you revisit your revisitation! I believe that having the option to use style cascading (as nature intended) to hide or change UI items that aren't currently available is useful and powerful. Having to write a bunch of event handlers to do the same thing is just boilerplate.

2. I'm excited to help you flesh this out going forward. It's surprising to me that it hasn't been the source of more issues. I know that my Snake demo - aside from being thoroughly silly - frequently doesn't work if you don't wait a few seconds for WS to upgrade the connection.

**Comment by hopsoft** [comment]
You talked me into it :)

**Pull request merged**
