### PR TITLE
 Pluralize the generated class name, so that will match with the file name

### PR DESCRIPTION
**Pull request by darkrubyist**
# Type of PR (feature, enhancement, bug fix, etc.)
bug fix

## Description
I notice in the SR screencast - Build a Twitter clone in 10 minutes with Rails, CableReady, and StimulusReflex: https://www.youtube.com/watch?v=F5hA79vKE_E that the Reflex generator is generating a singular class name. 

## Why should this be added
This PR should pluralize the generated class name, so that will match with the file name.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing

### CODE REVIEW

**Comment by marcoroth** [comment]
Good observation! I agree that the filename should match the defined class in it.

But is this really the wanted behaviour for every case? I wouldn't say that the reflex name should always be pluralized, because the reflex doesn't have to match to an according model. I think it would make sense if the behaviour would match the Rails controller generator.

This means that:
* `rails g stimulus_reflex posts` generates a `posts_reflex.rb` file which defines the `PostsReflex` class
* and `rails g stimulus_reflex post` generates a `post_reflex.rb` file which defines the `PostReflex` class

What do you think @darkrubyist?

**Comment by darkrubyist** [comment]
Thanks, @marcoroth. This commit should support both singular and plural use cases.

**Comment by marcoroth** [comment]
Nice, I like this addition! 🎉 

One little detail: Does it also make sense to update the reflex class references for consistency in the js comments of [custom_controller.js](https://github.com/hopsoft/stimulus_reflex/blob/master/lib/generators/templates/custom_controller.js) ?

**Comment by darkrubyist** [comment]
Thanks @marcoroth .  Updated the custom_controller.js and added tests for both scenarios.

I notice the `bundle exec rails d stimulus_reflex User` will remove the `application_controller.rb` and `application_controller.js` as well.

Do you think there is a way to not do that?

**Comment by marcoroth** [comment]
Yes there is. You can check the value of the `behavior` variable. The value is either `:invoke` or `:revoke`. 

Something like this should do the trick:
```ruby
if behavior == :invoke
  template "application_reflex.rb", File.join(REFLEX_BASE_PATH, "application_reflex.rb")
end
```

**Comment by hopsoft** [comment]
Great observation and addition. I'm happy to merge this once conflicts are resolved and we update to prevent removing of the application controller files.

**Comment by leastbad** [comment]
Huzzah! Congratulations to @darkrubyist on a great PR. Thanks @marcoroth for your contributions.

**Comment by leastbad** [comment]
QQ: Just so everything lines up just right, do I need to tweak anything in this section? https://docs.stimulusreflex.com/quickstart#stimulusreflex-generator

**Comment by darkrubyist** [comment]
Thanks @hopsoft, @leastbad, @marcoroth for help. :)

Now, we support both singular and plural versions, so users can use:

`bundle exec rails generate stimulus_reflex user`
`bundle exec rails generate stimulus_reflex users`

`application_reflex.rb` and `application_controller.js` will not be removed anymore if the user will run `bundle exec rails d stimulus_reflex user` or `bundle exec rails d stimulus_reflex users`.

@leastbad, @hopsoft recommended the use of the plural version, similar to rails controllers.

**Pull request merged**
